### PR TITLE
Distribute authelia-scripts in docker image

### PR DESCRIPTION
**Pull request by kusold**
Building and copying the authelia-scripts binary so that migrations can
easily be ran.

Closes: https://github.com/clems4ever/authelia/issues/515

### CODE REVIEW

**Comment by clems4ever** [comment]
Hello @kusold , thank you for your contribution. Can you please add authelia-scripts to all dockerfiles?

**Comment by kusold** [comment]
Added to the other dockerfiles. Are the tests known to be flaky? I'd be surprised if this actually broke anything.

**Comment by nightah** [comment]
No Travis has been playing up lately due to it's package mirrors.

@kusold could you please rebase from master and squash your commits? Once that's done we should be good to merge this in.

**Comment by nightah** [comment]
Thanks @kusold for your contribution.

**Comment by clems4ever** [comment]
Thank you @kusold !

**Comment by nightah** [comment]
@clems4ever we need to revisit this later to only make the migration portion part of the primary authelia binary, or only compiling that element in, since we have the whole authelia-scripts toolchain it's double the size of our docker container.

**Pull request merged**
