### PR TITLE
fix(handlers): align response status codes for the verify endpoint

### PR DESCRIPTION
**Pull request by james-d-elliott**
This aligns all response status codes on the /api/verify endpoint when an error occurs, making it impossible to determine the actual reason for the failure.

### CODE REVIEW

**Comment by clems4ever** [comment]
LGTM

**Review by clems4ever — APPROVED** [review]
LGTM

**Comment by landloos** [comment]
Thought I'd just report that this broke my Authelia. I just get a blank page instead of the login page from this version (4.29.3) onwards. If I roll back to 4.29.2 it works. I use the official docker images.

**Comment by nightah** [comment]
This was due to a library bump, the issue has already been resolved in `4.29.4`.

**Comment by landloos** [comment]
Thanks. I'll go and update to that and check again.

**Pull request merged**
