### PR TITLE
fix(session): redis logging

### PR DESCRIPTION
**Pull request by james-d-elliott**
This hooks the go-redis logging so the messages are displayed as trace via our logging tool.

### CODE REVIEW

**Review by nightah — APPROVED** [review]
LGTM.

**Comment by yesraazazmeh5** [comment]
rr0827471@gmail.com

**Comment by yesraazazmeh5** [comment]
bba615523@gmail.com

**Comment by yesraazazmeh5** [comment]
> This hooks the go-redis logging so the messages are displayed as trace via our logging tbba615523@gmail.com

**Pull request merged**
