### PR TITLE
docs: fix broken url in config.template.yml

### PR DESCRIPTION
**Pull request by mpdcampbell**
Tiny PR to fix a broken link to the SameSite cookie documention in the comments of config.template.yml

### CODE REVIEW

**Comment by nightah** [comment]
Thanks for the PR @mpdcampbell can you please also replicate the change in `internal/configuration/config.template.yml`?

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Comment by mpdcampbell** [comment]
Sorry @nightah, I didn't spot that file. Change made.

**Comment by nightah** [comment]
No problems at all, thanks again @mpdcampbell!

**Comment by james-d-elliott** [comment]
@all-contributors please add @mpdcampbell for docs

**Pull request merged**
