### PR TITLE
Add NEXTAUTH_URL for homarr config, needed in revese proxy setup

### PR DESCRIPTION
**Pull request by rkj**
Without it the redirect goes to localhost:7575 instead of to the correct domain and the flow fails.

More details in https://github.com/ajnart/homarr/issues/1909

### CODE REVIEW

**Comment by james-d-elliott** [comment]
Appreciate the PR @rkj. The concern I have is they appear to have fixed it. Could you elaborate a bit more about your setup? What proxy are you using?

**Comment by rkj** [comment]
I'm using Caddy, nothing fancy in the config. I have 4 other apps already configured with Authelia and they work without problem with the configs from Authelia's integration (just with ids&secrets regenerated).

Here's my Homarr config if relevant:
```
❯ cat docker-compose.yml 
services:
  homarr:
    image: ghcr.io/ajnart/homarr:0.15.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - configs:/app/data/configs
      - data:/data
      - icons:/app/public/icons
    ports:
      - '7575:7575'
    environment:
      - BASE_URL=homarr.example.me
      - TZ=America/Los_Angeles
      - DEFAULT_COLOR_SCHEME=dark
      - AUTH_PROVIDER=credentials,oidc
      - AUTH_OIDC_URI=https://authelia.example.me
      - AUTH_OIDC_CLIENT_ID=random string
      - AUTH_OIDC_CLIENT_SECRET=topsecret
      - AUTH_OIDC_CLIENT_NAME=Authelia
      - AUTH_LOGOUT_REDIRECT_URL=https://authelia.example.me/logout
      - AUTH_OIDC_ADMIN_GROUP=sudoers-users
      - AUTH_OIDC_OWNER_GROUP=sudoers-owners
      - NEXTAUTH_URL=https://homarr.alrk.me
```

**Comment by james-d-elliott** [comment]
Nah caddy and traefik are identical in the relevant headers. I think we'll commit this for now but if you can reach out to devs and try to figure it out so we don't have to include this that'd be awesome.

**Comment by rkj** [comment]
Thank you! Commented https://github.com/ajnart/homarr/issues/1909#issuecomment-2398032134 - if it gets resolved I'll update it back.

Thanks for this awesome project!

**Pull request merged**
