### PR TITLE
Updated secrets.md with a functional DaemonSet

### PR DESCRIPTION
**Pull request by thehedgefrog**
I noticed the example on the website had several issues and updated it with a  working version:
- Indentation now fixed
- Changed *AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE* for *AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE* to match the documentation
- Added missing *AUTHELIA_SESSION_REDIS_PASSWORD_FILE* in spec.containers.env
- Changed container port to 9091 to match necessary port
- Changed Probes to tcpSocket from httpGet
- Removed non-functional localtime volume
- Unintended: trimmed white space in the document

### CODE REVIEW

**Review by james-d-elliott — COMMENTED** [review]
Mostly LGTM. Question, why use  TCP socket instead of one of the API endpoints?

I know configuration no longer works (we changed it to require auth), but the following would also work:

```
          readinessProbe:
            httpGet:
              path: /api/state
              port: authelia-port
            initialDelaySeconds: 15
```

**Comment by thehedgefrog** [comment]
You're right, I tried a few API endpoints and it didn't work, so I went to the lowest common denominator.

**Comment by nightah** [comment]
@thehedgefrog do you mind changing back to the `/api/state` endpoint and rebasing from master?

**Comment by thehedgefrog** [comment]
> 
> 
> @thehedgefrog do you mind changing back to the `/api/state` endpoint and rebasing from master?

Should be all good now.

**Review by james-d-elliott — APPROVED** [review]

**Pull request merged**
