### PR TITLE
Fix issue with nextcloud 

### PR DESCRIPTION
**Pull request by jbperrin88**
Modify token_endpoint_auth_method to resolved issue:

image

https://github.com/nextcloud/user_oidc/issues/981

### CODE REVIEW

**Comment by hendrik1120** [comment]
I reported that like 5 months ago lol
Which version of nextcloud and user_oidc version are you using? It is still working fine for me, but I haven't touched it since last time.

**Comment by hendrik1120** [comment]
@jbperrin88 In case my question got lost in the bot noise.

If you also update the version in the docs for both Nextcloud and the plugin, it should be fine

**Comment by james-d-elliott** [comment]
Is this still needed?

**Comment by hendrik1120** [comment]
Imo you can close it and I will PR it with some other changes

**Pull request closed without merging**
