### PR TITLE
Update OIDC MinIO community content

### PR DESCRIPTION
**Pull request by georglauterbach**
Very minor doc update.

See minio/minio#12722. Updated callback URL and issue description.

### CODE REVIEW

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Comment by james-d-elliott** [comment]
Looking at their docs, you can just use MINIO_IDENTITY_OPENID_CLAIM_NAME=groups, this will use your group names as policies.

**Comment by georglauterbach** [comment]
> Looking at their docs, you can just use MINIO_IDENTITY_OPENID_CLAIM_NAME=groups, this will use your group names as policies.

I will test this later today and report back, thanks @james-d-elliott 👍🏼

**Comment by georglauterbach** [comment]
@james-d-elliott it works! Thank you very much for telling me :D

I will update the docs soon :)

**Pull request merged**
