### PR TITLE
[FEATURE] Add theme support

### LINKED ISSUE #113: Support custom theme in the client
Hi,

it would be quite a nice enhancement to be able to configure Authelia so that specific icons, title, text, email template, etc. are used instead of the default ones.

### PR DESCRIPTION
**Pull request by nightah**
This change allows users to select a theme for Authelia on start-up.

The default will continue to be the existing theme which is known as `light`.
 ~~Three~~ Two new options are now also provided:
* `dark`
* `grey`
* ~~`custom`~~

~~The `custom` theme allows users to specify a primary and secondary hex color code to be utilised to style the portal.~~

Closes #113.

Co-authored-by: BankaiNoJutsu <lbegert@gmail.com>

### CODE REVIEW

**Comment by nightah** [comment]
Here's some screenshots of the themes:

**Light:**
Screenshot_2021-01-06-05-24-31_2560x1440
Screenshot_2021-01-06-05-25-31_2560x1440

**Dark:**
Screenshot_2021-01-06-05-25-56_2560x1440
Screenshot_2021-01-06-05-26-29_2560x1440

**Grey:**
Screenshot_2021-01-06-05-26-58_2560x1440
Screenshot_2021-01-06-05-27-33_2560x1440

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Comment by zhdenny** [comment]
I don't understand. I've been running standard authelia/authelia from dockerhub......I saw Theme Support has been added.
I got to my configuration.yml and add this:

```
# The theme to display: light, dark, grey
theme: light
```

Authelia fails to restart.....just plain doesn't start up.

**Comment by nightah** [comment]
This feature does work with the `master` tagged container.

Until there's a new release that's the only tag that includes this feature.

**Comment by randomnameforgithub** [comment]
Hello,I saw that custom theme has been removed (probably for good reasons). May I suggest allowing custom css? Or at least add basic stuff such as background colour or profile pic to a config file. Thanks.

**Comment by designermonkey** [comment]
I am interestd in knowing why a custom theme folder was omitted also as I understood it to be the main jist of the issue that spawned this PR? Is there any info on why it was omitted?

**Comment by MarcinWArdentCode** [comment]
Hey, what's the current status of custom themes for Authelia? Is it possible to at least add custom CSS and swap images?

**Pull request merged**
