### PR TITLE
Reflect change of 9ae2096 on the redirection param

### PR DESCRIPTION
**Pull request by SilverBut**
In commit 9ae2096, the redirection parameter is changed in the example `nginx.conf`, and also in other places like `internal/middlewares/identity_verification.go`:

```
- link := fmt.Sprintf("%s://%s/#%s?token=%s", ctx.XForwardedProto(),
+ link := fmt.Sprintf("%s://%s%s?token=%s", ctx.XForwardedProto(),
```

### CODE REVIEW

**Comment by SilverBut** [comment]
Also add changes for `BREAKING.md`. Change my text if you want ;)

**Comment by nightah** [comment]
Thanks @SilverBut this has been discussed enough times already and I've forgotten to fix this up.
There's also a reference to the hash router in line 40 of the `README.md` can you remove it there too please?

**Comment by nightah** [comment]
Thanks @SilverBut!

**Comment by SilverBut** [comment]
> There's also a reference to the hash router in line 40 of the `README.md` can you remove it there too please?

Haven’t noticed, sorry. Do you mean these two files? Now committed.
```
➜ grep -rn . -e '#/'
./example/kube/README.md:40:`nginx.ingress.kubernetes.io/auth-signin: "https://login.example.com:8080/#/"`
./example/kube/apps/apps.yml:78:    nginx.ingress.kubernetes.io/auth-signin: "https://login.example.com:8080/#/"
```

**Comment by SilverBut** [comment]
Oops seems my action is kinda slow...

**Comment by nightah** [comment]
It's okay @SilverBut I've adjusted accordingly, thanks for your contribution.

**Comment by clems4ever** [comment]
Thanks @SilverBut .

**Pull request merged**
