### PR TITLE
fix: oidc issuer path and strip path middleware

### LINKED ISSUE #2260: OIDC: Path issues
### Description

As discussed in chat, there are some issues with OIDC when using the path middleware 

### Expected Behaviour

_N/A_

### Reproduction Steps

_N/A_

### Additional Information

_**Note 1 (james-d-elliott):** Currently the only known fix is to configure Authelia and NGINX to use subdomain configuration. This will work for the user in question, but other users will experience issues in the future. It would be good if we fix this to get as much information from Bradley as possible in order to replicate it. I believe currently he's using a fairly stock swag configuration, with the path set to `authelia`. We should make sure in his case that the sections we change are commented out and replaced so reverting to his old configuration if he desires is a very simple adjustment._

### PR DESCRIPTION
**Pull request by nightah**
This ensures the server.path requests append the base_url to the oidc well-known issuer information and adjusts server.path configuration to only strip the configured path instead of the first level entirely, regardless of its content.

Co-authored-by: James Elliott <james-d-elliott@users.noreply.github.com>

Fixes #2260, Closes #2257, Closes #2258.

### CODE REVIEW

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Review by james-d-elliott — CHANGES_REQUESTED** [review]
I think we still have to change `handleOIDCWorkflowResponse` to use ctx.GetExternalRootURL?

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Comment by BCNelson** [comment]
This Worked for me and fixed #2260

**Pull request merged**
