### PR TITLE
Grafana dashboard

### PR DESCRIPTION
**Pull request by webysther**
Per https://github.com/authelia/authelia/discussions/6376#discussioncomment-7770125

screencapture-monitor-webysther-org-d-ab5effea-4f31-453d-8945-fc1519146752-single-sign-on-2023-12-09-19_31_46

### CODE REVIEW

**Comment by webysther** [comment]
screencapture-monitor-webysther-org-d-ab5effea-4f31-453d-8945-fc1519146752-single-sign-on-2023-12-09-19_31_46

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Comment by Lebowski89** [comment]
> Per [#6376 (reply in thread)](https://github.com/authelia/authelia/discussions/6376#discussioncomment-7770125)

Hi web,

You've included the UID for your prometheus in the json. Adding to grafana resulted in errors/data source not found. No option to pick an initial data source or change the included data source. I had to edit out all references to the included prometheus data source UID. I think you're supposed to choose to share your dashboard externally and it won't include your UID in the json.

**Comment by webysther** [comment]
> > Per [#6376 (reply in thread)](https://github.com/authelia/authelia/discussions/6376#discussioncomment-7770125)
> 
> Hi web,
> 
> You've included the UID for your prometheus in the json. Adding to grafana resulted in errors/data source not found. No option to pick an initial data source or change the included data source. I had to edit out all references to the included prometheus data source UID. I think you're supposed to choose to share your dashboard externally and it won't include your UID in the json.
> 
> The UID:
> 
> ```
> "uid": "PBFA97CFB590B2093"
> ```

Any chance to open a PR and remove to me please? I don't have time this week.

**Comment by Lebowski89** [comment]
> Any chance to open a PR and remove to me please? I don't have time this week.

Sure, I should have some time over the next couple of days.

**Pull request merged**
