### PR TITLE
Add config example for LDAP groupOfUniqueNames group structure

### PR DESCRIPTION
**Pull request by zmiguel**
Based on #1517 

Adding a comment to the LDAP group section of the config file to tell users they need to use a different group_filter if their LDAP groups use the `groupOfUniqueNames` structure instead of the expected `groupOfNames` structure.

Not doing so result in Authelia not finding the groups for the user and not authorizing group-based access.

### CODE REVIEW

**Review by james-d-elliott — CHANGES_REQUESTED** [review]
LGTM, which LDAP standard/backend are you using? RFC4519?

Also just need to adjust this file too (same change as the config template):

https://github.com/authelia/authelia/blob/master/docs/configuration/authentication/ldap.md

**Comment by zmiguel** [comment]
> LGTM, which LDAP standard/backend are you using? RFC4519?

I'm using OpenLDAP configured to use RFC2307BIS_SCHEMA

I initialized my LDAP database using the _[wheelybird/ldap-user-manager](https://hub.docker.com/r/wheelybird/ldap-user-manager)_ docker container that uses `groupOfUniqueNames` by default for groups.

This pull request is to provide more information to new users that might be using the same setup on their docker deployments that they need to change the group filter so authelia correctly picks up the groups for the given username.

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Comment by james-d-elliott** [comment]
I was just curious for the future, it's nice to know what our users are using so we can setup LDAP implementation templates like this: https://www.authelia.com/docs/configuration/authentication/ldap.html#implementation

Thanks for contributing! If you were interested in contributing in a future PR we could assist either via GitHub, Matrix, or Discord (see badges on https://github.com/authelia/authelia to join Matrix/Discord).

**Pull request merged**
