### PR TITLE
fix(session): change keyprefix of redis provider

### LINKED ISSUE #2323: Authelia seems not to work with open-source version of Redis Sentinel
## Bug Report

Using authelia v4.30.4 with Redis version 6.2.5 in Sentinel mode is not possible. It seems that lack of hashing policies in open-source version causes issues because Authelia uses non-standard key format.

### Description

Log-in attempt causes the following error:
```
level=error msg="Unable to regenerate session for user daniel: CROSSSLOT Keys in request don't hash to the same slot" method=POST path=/api/firstfactor remote_ip=83.22.35.182 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:66  (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/handlers/response.go:148            handleAuthenticationUnauthorized\ngithub.com/authelia/authelia/v4/internal/handlers/handler_firstfactor.go:144 FirstFactorPost.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:51  AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.1/router.go:414                              (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14       LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.28.0/server.go:2239                           (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.28.0/workerpool.go:223                        (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.28.0/workerpool.go:195                        (*workerPool).getCh.func1\nruntime/asm_amd64.s:1371                                                     goexit"
```

Redis docs: https://redis.com/blog/redis-clustering-best-practices-with-keys/

Key format used, which is incompatible with default hashing policy
```
127.0.0.1:6379> seckeys *
1) "authelia-session:##REDACTED##"
127.0.0.1:6379> 
```

If you changed format to `authelia-session{##SESSION_KEY##}` it should work.

### Expected Behaviour

_N/A_

### Reproduction Steps

_N/A_

### Additional Information

configuration section:
```
session:
  name: authelia_session
  secret: ##REDACTED##
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M
  domain: ##REDACTED##
  redis:
    username: authelia
    password: ##REDACTED##
    tls:
      server_name: redis-master.rlyeh.ds
      skip_verify: false
      minimum_version: TLS1.2
    high_availability:
      sentinel_name: redis01
      sentinel_password: ##REDACTED##
      nodes:
        - host: redis01
          port: 26379
        - host: redis02
          port: 26379
        - host: redis03
          port: 26379
```

### PR DESCRIPTION
**Pull request by danielskowronski**
Change KeyPrefix of Redis provider by wrapping it in curly braces, so all entries are stored in single slot.

Hashing algorithm of open-source Redis (including Sentinel) does not allow customization, but has one built-in policy: if curly braces are found, string in it is taken as input to hashing function instead if entire key. https://redis.com/blog/redis-clustering-best-practices-with-keys/

This resolves #2323 where `CROSSSLOT` error occurred.

### CODE REVIEW

**Comment by james-d-elliott** [comment]
Looking at their implementation documentation of this feature, wouldn't it be more prudent to wrap the session id part? The current implementation will return the same slot for every user session as I understand it.

**Comment by james-d-elliott** [comment]
I accidentally hit update branch on this instead of one of mine! Apologies.

**Comment by james-d-elliott** [comment]
@danielskowronski did you see this comment? https://github.com/authelia/authelia/pull/2324#issuecomment-912951114

**Comment by danielskowronski** [comment]
Correct me if I'm wrong, but you can't have Sentinel without regular cluster underneath, can you? In my setup, Authelia has 3 sentinel endpoints configured.

I'm not sure what is happening in the library used for Redis, but even when I had one session, it was throwing `CROSSSLOT` - that led me to wrap the entire prefix in `{}`. Moreover, session ID is combined with prefix inside 3rd party library, so not sure how to handle that.

I'll spawn a dedicated environment for that and share my full configs.

**Comment by james-d-elliott** [comment]
> Correct me if I'm wrong, but you can't have Sentinel without regular cluster underneath, can you? In my setup, Authelia has 3 sentinel endpoints configured.

Actually you definitely can. Redis Cluster was added  after Redis Sentinel since Sentinel addressed availability issues in Redis itself, but it didn't address scaling issues. 

> This is log from server run:

Is this error occurring with your changes?

> I'm not sure what is happening in the library used for Redis, but even when I had one session, it was throwing `CROSSSLOT` - that led me to wrap the entire prefix in `{}`. Moreover, session ID is combined with prefix inside 3rd party library, so not sure how to handle that.

Regarding this, the upstream session library does not at this time utilize the go redis NewCluster func which newup's a Redis Cluster config: https://github.com/go-redis/redis/blob/master/cluster.go#L705-L724

If you're  running into issues with your changes, I can look at implementing that as a provider for testing then we can implement it upstream.

**Comment by danielskowronski** [comment]
The log is from upstream version (that should be posted in issue I raised, not PR...)

I'll need to dig even deeper into Redis then, I might have made some incorrect assumptions.

**Comment by danielskowronski** [comment]
Ugh, it appears I confused Redis Cluster setup (even having 1 master and multiple slaves) with Redis setup with `replicaof`. And having Sentinel on to of that made me super confused.

Making Pull Request was easier than figuring it out from Redis documentation :|

Anyway, there's still one weird thing that resides in session library - why even on single key in Redis it was failing with `CROSSSLOT` - I'll try to look at it some day.

**Pull request closed without merging**
